http:
  middlewares:
    jwt-auth:
      plugin:
        jwt-validation-middleware:
          secret: CsnCr3lebs9eJQ
          optional: false
          forwardAuth: false

  routers:
    modelbazaar-http:
      rule: "PathPrefix(`/api`)"
      priority: 10
      service: "modelbazaar-service"
    frontend-http:
      rule: "PathPrefix(`/`)"
      priority: 1
      service: "frontend-service"

  services:
    modelbazaar-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"
    
    frontend-service:
      loadBalancer:
        servers:
          - url: "http://localhost:3006"
