http:
  routers:
    modelbazaar-http:
      rule: "(PathPrefix(`/api`) && !PathPrefix(`/api/auth`))"
      priority: 10
      service: "modelbazaar-service"
      middlewares:
        - "limit-body-size"

    frontend-http:
      rule: "(PathPrefix(`/api/auth`) || PathPrefix(`/`))"
      priority: 1
      service: "frontend-service"

  services:
    modelbazaar-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://localhost:3006"

  middlewares:
    limit-body-size:
      buffering:
        maxRequestBodyBytes: 524288000
        memRequestBodyBytes: 20971520
