http:
  routers:
    keycloak-http:
      rule: "PathPrefix(`/api/auth`)"
      priority: 10
      service: "keycloak-service"
    modelbazaar-http:
      rule: "PathPrefix(`/api`)"
      priority: 10
      service: "modelbazaar-service"
    frontend-http:
      rule: "PathPrefix(`/`)"
      priority: 1
      service: "frontend-service"

  services:
    keycloak-service:
      loadBalancer:
        servers:
          - url: "http://localhost:3006"

    modelbazaar-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://localhost:3006"
