http:
  routers:
    modelbazaar-http:
      rule: "(PathPrefix(`/api`) && !PathPrefix(`/api/auth`))"
      priority: 10
      service: "modelbazaar-service"

    frontend-http:
      rule: "(PathPrefix(`/api/auth`) || PathPrefix(`/`))"
      priority: 1
      service: "frontend-service"

    keycloak-http:
      rule: "PathPrefix(`/keycloak`)"
      priority: 10
      service: "keycloak-service"

  services:
    modelbazaar-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://localhost:3006"

    keycloak-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8180"
