NDB:
  config: scifact
  check_unsupervised_supervised:
    dependencies: []
    params:
      sharded: variable      # Use the value of the "sharded" variable
      run_name: variable      # Use the value of the "run_name" variable
      config: variable        # Use the value of the "config" variable

  await_train:
    dependencies: [check_unsupervised_supervised]    # Depends on the completion of the "check_unsupervised_supervised" task
    params:
      model: check_unsupervised_supervised           # Use the output of the "check_unsupervised_supervised" task as the "model" parameter

  deploy_ndb:
    dependencies: [await_train]           # Depends on the completion of the "await_train" task
    params:
      model: check_unsupervised_supervised           # Use the output of the "check_unsupervised_supervised" task as the "model" parameter
      run_name: variable                  # Use the value of the "run_name" variable

  await_deploy:
    dependencies: [deploy_ndb]                # Depends on the completion of the "deploy" task
    params:
      deployment: deploy_ndb                  # Use the output of the "deploy" task as the "deployment" parameter

  check_search:
    dependencies: [await_deploy]          # Depends on the completion of the "await_deploy" task
    params:
      deployment: deploy_ndb                  # Use the output of the "deploy" task as the "deployment" parameter

  check_deployment_ndb:
    dependencies: [check_search]          # Depends on the completion of the "await_deploy" task
    params:
      deployment: deploy_ndb                  # Use the output of the "deploy" task as the "deployment" parameter
      config: variable                    # Use the value of the "config" variable
      results: check_search
  
  undeploy:
    dependencies: [check_deployment_ndb]      # Depends on the completion of the "check_deployment" task
    params:
      deployment: deploy_ndb                  # Use the output of the "deploy" task as the "deployment" parameter

UDT:
  config: [token, text]
  check_udt_train:
    dependencies: []
    params:
      run_name: variable      # Use the value of the "run_name" variable
      config: variable        # Use the value of the "config" variable

  await_train:
    dependencies: [check_udt_train]  # Depends on the completion of the "check_udt_train" task
    params:
      model: check_udt_train          # Use the output of the "check_udt_train" task as the "model" parameter
  
  udt_deploy:
    dependencies: [await_train]           # Depends on the completion of the "await_train" task
    params:
      model: check_udt_train           # Use the output of the "check_udt_train" task as the "model" parameter
      run_name: variable                  # Use the value of the "run_name" variable
      config: variable

  await_deploy:
    dependencies: [udt_deploy]                # Depends on the completion of the "deploy" task
    params:
      deployment: udt_deploy                  # Use the output of the "deploy" task as the "deployment" parameter

  check_search:
    dependencies: [await_deploy]          # Depends on the completion of the "await_deploy" task
    params:
      deployment: udt_deploy                  # Use the output of the "deploy" task as the "deployment" parameter

  undeploy:
    dependencies: [check_search]      # Depends on the completion of the "check_search" task
    params:
      deployment: udt_deploy                  # Use the output of the "deploy" task as the "deployment" parameter