NDB:
  config: scifact
  check_unsupervised_supervised:
    dependencies: []
    params:
      sharded: variable
      run_name: variable
      config: variable

  await_train:
    dependencies: [check_unsupervised_supervised]
    params:
      model: check_unsupervised_supervised

  deploy_ndb:
    dependencies: [await_train]
    params:
      model: check_unsupervised_supervised
      run_name: variable

  await_deploy:
    dependencies: [deploy_ndb]
    params:
      deployment: deploy_ndb

  check_search:
    dependencies: [await_deploy]
    params:
      deployment: deploy_ndb

  check_deployment_ndb:
    dependencies: [check_search]
    params:
      deployment: deploy_ndb
      config: variable
      results: check_search
  
  undeploy:
    dependencies: [check_deployment_ndb]
    params:
      deployment: deploy_ndb

  check_unsupervised:
    dependencies: [await_train]
    params:
      sharded: variable
      run_name: variable
      config: variable
      base_model: check_unsupervised_supervised
      file_num: 1
      test: True

  await_train_2:
    function: await_train
    dependencies: [check_unsupervised]
    params:
      model: check_unsupervised

UDT:
  config: [token, text]
  check_udt_train:
    dependencies: []
    params:
      run_name: variable
      config: variable

  await_train:
    dependencies: [check_udt_train]
    params:
      model: check_udt_train
  
  udt_deploy:
    dependencies: [await_train]
    params:
      model: check_udt_train
      run_name: variable
      config: variable

  await_deploy:
    dependencies: [udt_deploy]
    params:
      deployment: udt_deploy

  check_search:
    dependencies: [await_deploy]
    params:
      deployment: udt_deploy

  undeploy:
    dependencies: [check_search]
    params:
      deployment: udt_deploy

AdminFunctions:
  config: ""
  test_add_admin:
    dependencies: []
    params:
      email: "test1user@mail.com"

  delete_user:
    dependencies: [test_add_admin]
    params:
      user_id: "user_id_from_previous_step"

  test_add_key:
    dependencies: [test_add_admin]
    params:
      user_id: "user123"
      key: "AWS_ACCESS_TOKEN"
      value: "aws_secret_value"

  test_get_key:
    dependencies: [test_get_key]
    params:
      user_id: "user123"
      key: "AWS_ACCESS_TOKEN"
