# the checkpoints for different logs will be stored in this directory
data_dir: ${SHARE_DIR}/logs

sources:
  # fetching logs for all models
  training_logs:
    type: file
    include:
      - "${SHARE_DIR}/logs/*/train.log"
    read_from: beginning

  deployment_logs:
    type: file
    include:
      - "${SHARE_DIR}/logs/*/deployment.log"
    read_from: beginning

transforms:
  parse_logs:
    # loads the json line as it is. we can add more fields here if needed
    # for example the IP address of the machine where the logs are generated
    type: remap
    inputs:
      - training_logs
      - deployment_logs
    source: |
      . = parse_json!(.message)

  # create two different sources for debug and non-debug logs
  filter_debug_logs:
    type: filter
    inputs:
      - parse_logs
    condition: |
      .level == "DEBUG"
  
  filter_non_debug_logs:
    type: filter
    inputs:
      - parse_logs
    condition: |
      .level != "DEBUG"

sinks:
  # two different sinks for debug and non-debug logs.
  # the number of debug logs can be high hence, we store them for a short period
  # retention period of debug logs is 48 hours, non debug logs are stored for 30 days
  debug_logs:
    type: http
    inputs:
      - filter_debug_logs
    uri: "${PRIVATE_MODEL_BAZAAR_ENDPOINT}victorialogs/insert/jsonline?_stream_fields=model_id,service_type&_msg_field=_msg&_time_field=_time&extra_fields=retention=48h"
    encoding:
      codec: json
    framing:
      method: newline_delimited
    request:
      headers:
        Content-Type: application/json
    healthcheck:
      enabled: false

  other_logs:
    type: http
    inputs:
      - filter_non_debug_logs
    uri: "${PRIVATE_MODEL_BAZAAR_ENDPOINT}victorialogs/insert/jsonline?_stream_fields=model_id,service_type&_msg_field=_msg&_time_field=_time&extra_fields=retention=30d"
    encoding:
      codec: json
    framing:
      method: newline_delimited
    request:
      headers:
        Content-Type: application/json
    healthcheck:
      enabled: false