{
 "title": "Chat",
 "description": "Chat interface dashboard",
 "time": { "from": "2024-12-27T05:46:15.312Z", "to": "2024-12-27T05:50:31.156Z" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "workload", "label": "Workload", "query": { "query": "label_values(exported_job)" } }
  ]
 },
 "panels": [
  {
   "title": "Conversation count",
   "type": "timeseries",
   "description": "Number of conversational messages",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (chat_query_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "timeseries",
   "description": "Average response time of a chat message",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum (chat_response_time_sum{job=\"deployment-jobs\",workload=\"$workload\"}) / sum (chat_response_time_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Satisfaction score",
   "type": "timeseries",
   "description": "Ratio of upvotes to the number of feedbacks",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (ndb_chat_upvote_metric_total{job=\"deployment-jobs\",workload=\"$workload\"}) / (sum (ndb_chat_upvote_metric_total{job=\"deployment-jobs\",workload=\"$workload\"}) + sum (ndb_chat_downvote_metric_total{job=\"deployment-jobs\",workload=\"$workload\"}))",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Repeated Questions",
   "type": "timeseries",
   "description": "Count of repeated questions.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum (ndb_chat_same_question_total{job=\"deployment-jobs\",workload=\"$workload\"}) / (sum (ndb_chat_same_question_total{job=\"deployment-jobs\",workload=\"$workload\"}) + sum (chat_query_count{job=\"deployment-jobs\",workload=\"$workload\"}))",
     "legendFormat": "value"
    }
   ]
  }
 ]
}