{
 "title": "Search model",
 "description": "Performance, usage stats of the enterprise search model",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(nomad_client_allocs_cpu_allocated,exported_job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queries Processed",
   "type": "timeseries",
   "description": "Number of queries processed",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (ndb_query_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Upvotes",
   "type": "timeseries",
   "description": "Number of upvotes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum (ndb_upvote_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Associates",
   "type": "timeseries",
   "description": "Number of associates",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum (ndb_associate_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "timeseries",
   "description": "Number of documents inserted additionally.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum (ndb_insert_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "timeseries",
   "description": "Number of documents deleted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum (ndb_delete_count{job=\"deployment-jobs\",workload=\"$workload\"})",
     "legendFormat": "value"
    }
   ]
  }
 ]
}