azure:
  branches:
    local_registry:
      pull_credentials:
        password: 1N7CsVddLTv4+enVywVCgjOkDkMqpv63WenU0bWihF+ACRBVBnXz
        username: thirdaiplatform-pull-local-registry
      push_credentials:
        password: rt/BPKK778qUWXa3YZjHUTNsVc9MkwU53kydXmSscF+ACRAfiMQq
        username: thirdaiplatform-push-local-registry
      version: 0.0.1
    mshift:
      pull_credentials:
        password: uGpzj1Ylkgc+PBbQ5e3r1nEFC+BtiQK2cNeFdRW1NP+ACRCsrcq2
        username: thirdaiplatform-pull-mshift
      push_credentials:
        password: 6DSwbtoUZpFEsAEdV6bL9VpVK+8qJoRcn8li7VRgAz+ACRDNRKRx
        username: thirdaiplatform-push-mshift
      version: 0.0.12
    on-prem-llm:
      pull_credentials:
        password: lZit7mOLUB2e7j/Ak50OXCHer4EdaCUDZ8EVHbQnJj+ACRAP/xev
        username: thirdaiplatform-pull-on-prem-llm
      push_credentials:
        password: /6WCAtZuvdhWPyw2VTArrXEgaxOf/5J0NJHoXfflGX+ACRAcpvWw
        username: thirdaiplatform-push-on-prem-llm
      version: 0.0.6
    release-test:
      pull_credentials:
        password: ivG00o0TTx10TZDh6Y4chVxDEGR92h0ib4uA5WjF2H+ACRC95ggs
        username: thirdaiplatform-pull-release-test
      push_credentials:
        password: c3P3qKGzI2dBE6fiKJfF+zHos70aRFcJ6vVLZh+zq0+ACRCEzI7T
        username: thirdaiplatform-push-release-test
      version: 0.0.18
    test_1:
      pull_credentials:
        password: lfhxcL/qmrYP24rIH2vmRNSYV9ZlNCfxJyQI6E3kVi+ACRDjUz22
        username: thirdaiplatform-pull-test-1
      push_credentials:
        password: XCM9NnRa3ybEjKNbsZSl8eEio1VC3NHMOGCwqOXb/r+ACRCD4kbn
        username: thirdaiplatform-push-test-1
      version: 0.0.1
    test_2:
      pull_credentials:
        password: wgAJy1o7t1aybREkWMi8oQnsHxLg5eetcD98yyXpXY+ACRB5rap/
        username: thirdaiplatform-pull-test-2
      push_credentials:
        password: v5yOJruG8kxPB5jpr50OurWDYBRuc+lw+VmXV+p4QU+ACRBitPEC
        username: thirdaiplatform-push-test-2
      version: 0.0.2
    test_3:
      pull_credentials:
        password: /5bqfPyF2QlEKJ/Xo26ctZmZ7SAqYNaq6P+DVRaMI2+ACRCxY8ds
        username: thirdaiplatform-pull-test-3
      push_credentials:
        password: PkCR7YWr0zG/sW6rZex19qzQdR4A1QNg7RXWFKCBGt+ACRDolvsb
        username: thirdaiplatform-push-test-3
      version: 0.0.1
  registry: thirdaiplatform.azurecr.io
provider: azure
