azure:
  branches:
    release-ci:
      pull_credentials:
        password: Ov+4eWt/ojeOnGexHWTmNluBBtEMUoPNHFodeC8QOH+ACRCkdX5r
        username: testThirdaiPlatform
      push_credentials:
        password: Ov+4eWt/ojeOnGexHWTmNluBBtEMUoPNHFodeC8QOH+ACRCkdX5r
        username: testThirdaiPlatform
      version: 1.0.0
  registry: testthirdaiplatform.azurecr.io
provider: azure
