azure:
  branches:
    frontend-bug-admin-workflow-2:
      pull_credentials:
        password: 1F8wbBmMX9LLD6SEy/YCBG0sOoeuV715K9L+1qHiO6+ACRCJ43fx
        username: thirdaiplatform-pull-frontend-bug-admin-workflow-2
      push_credentials:
        password: fho4W31pDUVwO4BZBVCuZ+hZX9lJuOeaKWLuwoYfDY+ACRDsPwk8
        username: thirdaiplatform-push-frontend-bug-admin-workflow-2
      version: 0.0.1
    test_1:
      pull_credentials:
        password: lfhxcL/qmrYP24rIH2vmRNSYV9ZlNCfxJyQI6E3kVi+ACRDjUz22
        username: thirdaiplatform-pull-test-1
      push_credentials:
        password: XCM9NnRa3ybEjKNbsZSl8eEio1VC3NHMOGCwqOXb/r+ACRCD4kbn
        username: thirdaiplatform-push-test-1
      version: 0.0.1
    test_2:
      pull_credentials:
        password: wgAJy1o7t1aybREkWMi8oQnsHxLg5eetcD98yyXpXY+ACRB5rap/
        username: thirdaiplatform-pull-test-2
      push_credentials:
        password: v5yOJruG8kxPB5jpr50OurWDYBRuc+lw+VmXV+p4QU+ACRBitPEC
        username: thirdaiplatform-push-test-2
      version: 0.0.2
    test_3:
      pull_credentials:
        password: /5bqfPyF2QlEKJ/Xo26ctZmZ7SAqYNaq6P+DVRaMI2+ACRCxY8ds
        username: thirdaiplatform-pull-test-3
      push_credentials:
        password: PkCR7YWr0zG/sW6rZex19qzQdR4A1QNg7RXWFKCBGt+ACRDolvsb
        username: thirdaiplatform-push-test-3
      version: 0.0.3
  registry: thirdaiplatform.azurecr.io
provider: azure
