# name: Check Javascript Formatting

# # Kills old jobs from the same pr if we push a new commit
# # See https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# jobs:
#   prettier:
#     name: Prettier
#     runs-on: ubuntu-22.04
#     strategy:
#       matrix:
#         node-version: [20]
#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up pnpm
#         uses: pnpm/action-setup@v2
#         with:
#           version: 8

#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: "pnpm"

#       - name: Install dependencies
#         run: pnpm install -D
#         working-directory: ./frontend

#       - name: Check code formatting with Prettier
#         run: pnpm exec prettier . --check
#         working-directory: ./frontend
