name: Check Formatting

# Kills old jobs from the same pr if we push a new commit
# See https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  python-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare Black
        run: |
          sudo pip3 install black
      - name: Prepare isort
        run: |
          sudo pip3 install isort
      - name: Check Black format 
        run: |
          black  --check --diff --exclude "build|.venv|venv|.env|env|deps" .
      - name: Check isort format
        run: |
          isort --diff --check --profile black --skip-glob deps --skip _deps .

  js-format:
    name: Prettier
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          working-directory: ./frontend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ./frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install -D

      - name: Check code formatting with Prettier
        run: pnpm exec prettier . --check