name: Release Job

on:
  push:
    branches:
      - release-tar-ball

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH for cloning
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PLATFORM_INSTALLATION_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Platform repository
        run: |
          git clone git@github.com:ThirdAILabs/platform.git
          cd platform
          git fetch --all
          git checkout upload-model

      - name: Download and store the model
        run: |
          wget -O ./qwen2-0_5b-instruct-fp16.gguf https://huggingface.co/Qwen/Qwen2-0.5B-Instruct-GGUF/resolve/main/qwen2-0_5b-instruct-fp16.gguf?download=true

      - name: Ensure scripts directory exists
        run: mkdir -p ./platform/scripts

      - name: Copy driver script to parent directory
        run: |
          cp ./packaging/driver.sh ./driver.sh

      - name: Package platform, model, and driver into tarball
        run: |
          tar -czvf thirdai-platform-package.tar.gz ./platform ./qwen2-0_5b-instruct-fp16.gguf ./driver.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: thirdai-platform-package
          path: thirdai-platform-package.tar.gz
