name: Release Job

on:
  push:
    branches: [main, adds-local-registry]

jobs:
  package:
    runs-on: ubuntu-latest-8-cores

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH for cloning
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PLATFORM_INSTALLATION_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Platform repository
        run: |
          git clone git@github.com:ThirdAILabs/platform.git

      - name: Download and store the model
        run: |
          mkdir -p gen-ai-models
          wget -O gen-ai-models/qwen2-0_5b-instruct-fp16.gguf https://huggingface.co/Qwen/Qwen2-0.5B-Instruct-GGUF/resolve/main/qwen2-0_5b-instruct-fp16.gguf?download=true

      - name: Ensure scripts directory exists
        run: mkdir -p ./platform/scripts

      - name: Copy driver script to parent directory
        run: |
          cp ./packaging/driver.sh ./driver.sh

      - name: Copy config.yml to parent directory
        run: |
          cp ./platform/config.yml ./config.yml

      - name: Copy README.md to parent directory
        run: |
          cp ./packaging/README.md ./README.md

      - name: Upload platform package artifact
        uses: actions/upload-artifact@v3
        with:
          name: thirdai-platform-package
          path: thirdai-platform-package.tar.gz

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository \
            "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}

      - name: "Azure Login"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Docker Registry
        run: |
          docker login -u thirdaiplatform-pull-local-registry -p 1N7CsVddLTv4+enVywVCgjOkDkMqpv63WenU0bWihF+ACRBVBnXz  thirdaiplatform.azurecr.io

      - name: Set the branch name for release
        run: |
          branch_name="local_registry"
          echo "Docker image branch to build on is: $branch_name"
          echo "branch_name=$branch_name" >> $GITHUB_ENV  # Save the latest_tag to the environment file

      - name: Fetch the latest tag for thirdai_platform
        id: fetch_latest_tag
        run: |
          latest_tag=$(az acr repository show-tags --name thirdaiplatform \
            --repository thirdai_platform_${{ env.branch_name }} --orderby time_desc --output tsv | grep -v '^latest$' | head -n 1)
          echo "Latest tag is: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV  # Save the latest_tag to the environment file

      - name: Download Docker images using the latest tag
        run: |
          mkdir -p docker_images-${{ env.latest_tag }}

          # Pull and save images using the persisted ${{ env.latest_tag }} across steps
          images=(thirdai_platform_${{ env.branch_name }} data_generation_job_${{ env.branch_name }} train_job_${{ env.branch_name }} node_discovery_${{ env.branch_name }} deployment_job_${{ env.branch_name }} llm_dispatch_job_${{ env.branch_name }} frontend_${{ env.branch_name }} llm_cache_job_${{ env.branch_name }})

          for image in "${images[@]}"
          do
              echo "Pulling thirdaiplatform.azurecr.io/${image}:${{ env.latest_tag }}..."
              docker pull thirdaiplatform.azurecr.io/${image}:${{ env.latest_tag }}
              docker save -o docker_images-${{ env.latest_tag }}/${image}_${{ env.latest_tag }}.tar thirdaiplatform.azurecr.io/${image}:${{ env.latest_tag }}
          done

          docker pull thirdaiplatform.azurecr.io/nomad-autoscaler:0.3.7
          docker save -o docker_images-${{ env.latest_tag }}/nomad-autoscaler_0.3.7.tar thirdaiplatform.azurecr.io/nomad-autoscaler:0.3.7

          docker pull thirdaiplatform.azurecr.io/redis:7.4.0
          docker save -o docker_images-${{ env.latest_tag }}/redis_7.4.0.tar thirdaiplatform.azurecr.io/redis:7.4.0

          docker pull registry:2
          docker save -o docker_images-${{ env.latest_tag }}/registry_2.tar registry:2

          docker pull postgres:latest
          docker save -o docker_images-${{ env.latest_tag }}/postgres_latest.tar registry:2

          docker pull thirdaiplatform.azurecr.io/traefik:v2.10
          docker save -o docker_images-${{ env.latest_tag }}/traefik_v2.10.tar thirdaiplatform.azurecr.io/traefik:v2.10

          docker pull thirdaiplatform.azurecr.io/grafana:main-ubuntu
          docker save -o docker_images-${{ env.latest_tag }}/grafana_main-ubuntu.tar thirdaiplatform.azurecr.io/grafana:main-ubuntu

          docker pull thirdaiplatform.azurecr.io/loki:main
          docker save -o docker_images-${{ env.latest_tag }}/loki_main.tar thirdaiplatform.azurecr.io/loki:main

          echo "All images pulled and saved in the docker_images folder."

      - name: Package platform, model, driver, config, and README into tarball
        run: |
          tar -czvf thirdai-platform-package-${{ env.latest_tag }}.tar.gz ./platform ./gen-ai-models/qwen2-0_5b-instruct-fp16.gguf ./driver.sh ./config.yml ./README.md

      - name: Replace driver script with local registry version
        run: |
          cp ./packaging/driver_local_registry.sh ./driver.sh

      # TODO(pratik): remove once we merge the changes on main on ansible PR.
      - name: Update branch to local-registry
        run: |
          cd platform
          git fetch --all
          git checkout adds-local-registry

      - name: Package Docker images, driver script, config, and README into tarball
        run: |
          tar -czvf thirdai-platform-package-local-registry-${{ env.latest_tag }}.tar.gz ./docker_images ./driver.sh ./config.yml ./README.md

      - name: Upload platform package artifact
        uses: actions/upload-artifact@v3
        with:
          name: thirdai-platform-package-${{ env.latest_tag }}
          path: thirdai-platform-package-${{ env.latest_tag }}.tar.gz

      - name: Upload Docker images artifact
        uses: actions/upload-artifact@v3
        with:
          name: thirdai-platform-package-local-registry-${{ env.latest_tag }}
          path: thirdai-platform-package-local-registry-${{ env.latest_tag }}.tar.gz
