name: Release Job

on:
  push:
    branches:
      - release-tar-ball

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Clone ThirdAI Platform repository
        run: |
          git clone https://github.com/ThirdAILabs/platform.git
          cd platform
          git fetch --all
          git checkout upload-model

      - name: Download and store the model
        run: |
          mkdir -p ./platform/models
          wget -O ./platform/models/qwen2-0_5b-instruct-fp16.gguf https://huggingface.co/Qwen/Qwen2-0.5B-Instruct-GGUF/resolve/main/qwen2-0_5b-instruct-fp16.gguf?download=true

      - name: Copy driver script to platform
        run: |
          cp ./packaging/driver.sh ./platform/scripts/driver.sh

      - name: Package platform, model, and driver into tarball
        run: |
          tar -czvf thirdai-platform-package.tar.gz ./platform

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: thirdai-platform-package
          path: thirdai-platform-package.tar.gz
