name: Unit Tests

# Kills old jobs from the same pr if we push a new commit
# See https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PRODUCT_VERSION: "latest"
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    types: [checks_requested]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  backend-unit-tests:
    runs-on: ubuntu-latest
    services:
      # We need postgres because generate_random_uuid does not work with sqlite since 
      # it requires pg-crypto. Since these tests are just testing individual backend
      # endpoints, they do not require nomad, traefik, vault, etc. These are available
      # in the integration tests.
      # TODO(Nicholas): refactor out generate_random_uuid so we can use in simple
      # sqlite DB for unit tests
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: model_bazaar
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install dependencies
        run: |
          pip3 install -r thirdai_platform/requirements.txt
          pip3 install pytest
          pip3 install pyopenssl --upgrade

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done

      - name: Create Extension
        run: |
          export PGPASSWORD='password'
          psql -h localhost -U postgres -d model_bazaar -c "CREATE EXTENSION IF NOT EXISTS pgcrypto;"
          echo "DB_BASE_URI=postgresql://postgres:password@localhost:5432" >> $GITHUB_ENV

      - name: run unit tests
        run: |
          cd thirdai_platform
          python3 -m pytest tests -v

      - name: Stop Services
        if: always()
        run: |
          sudo systemctl stop postgresql

  train-job-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        pip3 install -r thirdai_platform/train_job/requirements.txt
        pip3 install -r thirdai_platform/platform_common/requirements.txt
        pip3 install pytest
        pip3 install pyopenssl --upgrade

    - name: run unit tests
      run: |
        cd thirdai_platform
        python3 -m pytest train_job -v
  
  llm-gen-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        pip3 install -r thirdai_platform/llm_dispatch_job/requirements.txt
        pip3 install httpx
        pip3 install pytest

    - name: run unit tests
      run: |
        cd thirdai_platform
        python3 -m pytest llm_dispatch_job -v

  deployment-job-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        pip3 install -r thirdai_platform/deployment_job/requirements.txt
        pip3 install -r thirdai_platform/platform_common/requirements.txt
        pip3 install pyopenssl --upgrade
        pip3 install pytest
        pip3 install thirdai[neural_db_v2]

    - name: run unit tests
      # These have to be run individually because otherwise global variables 
      # don't get reset correctly between tests. 
      # TODO(Nicholas): Refactor the deployment job to avoid this.
      run: |
        cd thirdai_platform
        python3 -m pytest deployment_job -k dev_mode[v1]
        python3 -m pytest deployment_job -k dev_mode[v2]
        python3 -m pytest deployment_job -k prod_mode[v1]
        python3 -m pytest deployment_job -k prod_mode[v2]